info:
  contact: {}
paths:
  /index:
    get:
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - HomePage
  /user/CreateUser:
    get:
      parameters:
      - description: User Name
        in: query
        name: name
        type: string
      - description: Enter password
        in: query
        name: password
        type: string
      - description: Enter password again
        in: query
        name: rePassword
        type: string
      responses:
        "200":
          description: code", "message"}
          schema:
            type: string
      summary: Add New User
      tags:
      - User
  /user/GetUserList:
    get:
      responses:
        "200":
          description: code", "message"}
          schema:
            type: string
      summary: All Users
      tags:
      - User
swagger: "2.0"
